export BUN_INSTALL="$HOME/.bun"
export PATH="$HOME/.bun/bin:$HOME/.local/bin:$HOME/.npm-global/bin:$HOME/.opencode/bin:$PATH"
export EDITOR="nvim"
export VISUAL="nvim"
export PAGER="less"

alias ll="ls -lah"
alias la="ls -A"
alias gs="git status"
alias gd="git diff"
alias gc="git commit"
alias gp="git pull"
alias gl="git log --oneline --graph --decorate -20"

if [[ $- == *i* ]] && command -v starship >/dev/null 2>&1; then
  eval "$(starship init bash)"
fi
