format = """
$directory\
$git_branch\
$git_status\
$character"""

[directory]
style = "bold #eeeeee"
truncation_length = 3

[git_branch]
format = "[$branch]($style)"
style = "#808080"

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "#fab283"

[character]
success_symbol = "[❯](bold #eeeeee)"
error_symbol = "[❯](bold #e06c75)"
